### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ArcticLatent** [emanuellopes/archLinuxPrime#1]
I'm really happy to find your work about Prime on Arch. I am an Arch fan and i struggled so much to get a working prime setup but no luck. Because of this i switched back to disgusting Windows. So before i try this work i want to ask some questions. Whats your system setup? What you have as nvidia and intel? How do you use this workaround? There is a tray icon in the taskbar to switch between nvidia and intel? Is it that simple?

Edit: Since i am going to install a clean arch should i install the nvidia propietary drivers and intell drivers at the same time?

Edit2: Ahh i am getting crazy. I cant get this work. Mate can you please provide the installation process? WHich drivers should i install to use this script? Rİght now when i try to swith nvidia it says 

`
error: target not found: lib32-mesa-libgl
resolving dependencies...
looking for conflicting packages...
:: nvidia-libgl and mesa-libgl are in conflict (libgl). Remove mesa-libgl? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: nvidia-libgl and mesa-libgl are in conflict

`

Thanks!

**Comment by emanuellopes** [comment]
HI, thanks for using my project!
I am sorry for late response!

Your problem is because you don't have multilib repository enabled in pacman :)

for that work you need edit /etc/pacman.conf and uncomment

[multilib]
Include = /etc/pacman.d/mirrorlist

https://wiki.archlinux.org/index.php/multilib
