### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by konstantingoretzki** [emanuellopes/archLinuxPrime#2]
Hey, are these scripts still working?
Would love to use this on my system.
Can you provide instructions on how to install/ what dependencies I need etc?

**Comment by emanuellopes** [comment]
Hi, just run ./install.sh for install.

for select graphic you need run prime-select nvidia or prime-select intel

**Comment by terriblespider** [comment]
Sorry for the late response. That's great, I'll definitely try this out. Is there anything to observe in terms of display managers? At the moment I use LightDM with the config of the arch wiki about Nvidia Optimus (current my nvidia GPU is all the time activated, and the intel is deactivated). https://wiki.archlinux.org/index.php/NVIDIA_Optimus#Using_nvidia
